create or replace TABLE <Database Name>.<Database Schema>.C_ING_PX_RECVR_CONFIG (
	TBL_ID NUMBER(38,0) autoincrement,
	RAW_TBL_NM VARCHAR(100),
	STG_TBL_NM VARCHAR(100),
	TRFN_TBL_NM VARCHAR(100),
	STRM_NM VARCHAR(100),
	RECVR_FLG VARCHAR(1)
);

create or replace TABLE <Database Name>.<Database Schema>.ING_PX_LOAD_LOG (
	TABLE_NM VARCHAR(100),
	FILE_NAME VARCHAR(250),
	CODE VARCHAR(10),
	MESSAGE VARCHAR(16777216),
	QUERYID VARCHAR(16777216),
	QUERYTEXT VARCHAR(16777216),
	SNAPSHOT_DT DATE,
	FILE_TS VARCHAR(20),
	FILE_SEQ VARCHAR(10),
	LOAD_TS TIMESTAMP_NTZ(9),
	LOAD_STATUS VARCHAR(10)
);

